version: 0.2
os: linux

# env:
#   parameter-store:
   

phases:
  install:
    commands:
      #- sudo apt-get update
      - ls -ltr
      - pwd
      - aws s3 --recursive ./dbr-aws-infra s3://dbr-artifact
# artifacts:
#   type: zip
#   files:
#     - '~/dbr-aws-infra'