version: 0.2
os: linux

# env:
#   parameter-store:
   

phases:
  install:
    commands:
      # - sudo apt-get update
      # - sudo apt install zip -y
      # - zip -r dbr-aws-infra.zip $CODEBUILD_SRC_DIR
      # - ls -ltr
      # - aws s3 cp --recursive ./dbr-aws-infra.zip s3://dbr-artifact
artifacts:
  type: zip
  files:
    - '.'